stages:
  - build
  - deploy

variables:
  CI_REGISTRY: cr.360world.com
  CI_REGISTRY_USER: cr-user
  CI_PROJECT_NAME: admin-dashboard-omnipresence
  IMAGE_TAG: $CI_COMMIT_TAG
  DOCKER_BUILDKIT: 1

docker-build:
  stage: build
  image:
    name: docker:23.0.6
  script:
    - apk add --no-cache bash curl
    - mkdir -p $HOME/.docker && touch $HOME/.docker/config.json
    - echo "{\"auths\":{\"https://${CI_REGISTRY}/v2/\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > $HOME/.docker/config.json
    # Build the Docker image
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG} .
    # Push the image to the registry
    - docker push ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG}
    # Remove the local build 
    - docker rmi ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG}
  rules:
    - if: $CI_COMMIT_TAG

k8s-deploy:
  stage: deploy
  image: curlimages/curl:8.7.1
  script:
    - sed -i -e 's|#IMAGE_VERSION#|'${CI_COMMIT_TAG}'|g' kubernetes/deployment.yaml
    - cat kubernetes/deployment.yaml
    - 'curl -k -X PUT https://prod-k8s.360world.com/apis/apps/v1/namespaces/prod-backend/deployments/admin-dashboard-omnipresence -H "Authorization: Bearer ${CI_K8S_TOKEN}" -H "Content-Type: application/yaml" --data-binary "@kubernetes/deployment.yaml"'
  dependencies:
    - docker-build
  rules:
    - if: $CI_COMMIT_TAG