// config/routes.ts
export const ROUTES = {
  PUBLIC: [
    { path: '/', name: 'Home' },
    { path: '/login', name: 'Login' },
    { path: '/signup', name: 'Signup' },
    { path: '/globe', name: 'Globe' },
  ],
  PROTECTED: [
    { path: '/dashboard', name: 'Dashboard Landing' },
    { path: '/dashboard/users', name: 'Users Dashboard' },
    { path: '/dashboard/users/all-users', name: 'All Users' },
    { path: '/dashboard/users/find-user', name: 'Find User' },
    { path: '/dashboard/users/active-users-sessions', name: 'Active Users Sessions' },
    { path: '/dashboard/rewards', name: 'Rewards Dashboard' },
    { path: '/dashboard/rewards/available-rewards', name: 'Available Rewards' },
    { path: '/dashboard/rewards/give-rewards', name: 'Give Rewards' },
    { path: '/dashboard/rewards/create-reward', name: 'Create Reward' },
    { path: '/dashboard/customersupport', name: 'Customer Support Dashboard' },
    { path: '/dashboard/customersupport/bug-report', name: 'Bug Report' },
    { path: '/dashboard/devops', name: 'Devops Dashboard' },
    { path: '/dashboard/devops/kubernetes', name: 'Kubernetes Dashboard' },
    { path: '/dashboard/analytics', name: 'Analytics Dashboard' },
    { path: '/dashboard/analytics/grafana', name: 'Grafana Dashboard' },
    { path: '/dashboard/analytics/call-history-table', name: 'Call History Table' },
    { path: '/dashboard/analytics/call-history-analytics', name: 'Call History Analytics' },
    { path: '/dashboard/analytics/active-user-analytics', name: 'Active User Analytics' },
    { path: '/dashboard/analytics/call-test-analytics', name: 'Call Test Analytics' },
    { path: '/dashboard/consumerpurchase', name: 'Consumer Purchase Dashboard' },
    { path: '/dashboard/consumerpurchase/available-offers', name: 'Available Offers' },
    { path: '/dashboard/consumerpurchase/create-offer', name: 'Create Offer' },
    { path: '/dashboard/location', name: 'Location Dashboard' },
    { path: '/dashboard/location/active-user-ids', name: 'Active User IDs' },
    { path: '/dashboard/location/user-priority', name: 'User Priority List' },
    { path: '/dashboard/location/blacklist-user', name: 'Blacklist User' },
    { path: '/dashboard/location/deny-list', name: 'Deny List' },
    { path: "/dashboard/mpsquare", name: "MP2 Dashboard" },
    { path: "/dashboard/mpsquare/users-in-jail", name: "Users in Jail" },
    { path: "/dashboard/mpsquare/add-to-jail", name: "Add Users to Jail" },
    { path: "/dashboard/mpsquare/dictionary", name: "Crime Dictionary" },
    { path: "/dashboard/sales", name: 'Sales Dashboard' },
    { path: "/dashboard/sales/sales-analytics", name: 'Sales Analytics' },
    { path: "/dashboard/remoteconfig", name: 'Remote Config Dashboard' },
    { path: "/dashboard/remoteconfig/sparrow-remote-config", name: 'Sparrow Remote Config' },
    { path: "/dashboard/demo", name: 'Demo Dashboard' },
    { path: "/dashboard/demo/globe", name: 'Demo Globe' },
    { path: "/dashboard/demo/globe2", name: 'Demo Globe 2' },
    { path: '/profile', name: 'Profile' },
    { path: '/admin', name: 'Admin Panel' },
    { path: '/admin/roles', name: 'Roles' },
    { path: '/admin/users', name: 'Users' },
    { path: '/admin/invitations', name: 'Invitations' },
  ]
} as const;
