---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: admin-dashboard-omnipresence
    group: backend
  name: admin-dashboard-omnipresence
  namespace: prod-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: admin-dashboard-omnipresence
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: admin-dashboard-omnipresence
      name: admin-dashboard-omnipresence
    spec:
      containers:
        - image: cr.360world.com/internal-web-apps/admin-dashboard-omnipresence:#IMAGE_VERSION#
          # envFrom:
          #   - configMapRef:
          #       name: admin-dashboard-omnipresence-config
          imagePullPolicy: IfNotPresent
          name: admin-dashboard-omnipresence
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: prod-cr
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: admin-dashboard-omnipresence
    group: backend    
  name: admin-dashboard-omnipresence
  namespace: prod-backend
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: admin-dashboard-omnipresence
  sessionAffinity: None
  type: ClusterIP